### ISSUE TITLE
Error: Flipper: Expected serializable (undefined, an array or an object). Got: null

### ISSUE THREAD

**Issue by fendorio** [realm/realm-flipper-plugin#115]
With the latest version of realm-flipper-device-plugin, one of the changes in the latest commit (https://github.com/realm/realm-flipper-plugin/commit/b1a2fdc6ba5667a70d1cd26ef3431a247c658299) is causing an issue with the react-native-flipper package.

On line 40 of the RealmPlugin.tsx file, this latest commit adds a null as the second parameter to the connection.send function, i.e. changing it from this 

```connection.send("getCurrentQuery");```

To this

``` connection.send("getCurrentQuery", null); ```

This causes an error to be thrown by the react-native-flipper package, all data passed to the "send" function is validated using the following function.

```
function assertSerializable(data) {
  if (
    data === undefined ||
    Array.isArray(data) ||
    (data && typeof data === 'object')
  ) {
    return true;
  }
  console.log("FLIPPER Data", data);
  throw new Error(
    'Flipper: Expected serializable (undefined, an array or an object). Got: ' +
      data,
  );
}
```

The newly passed null is causing the react-native-flipper package to throw an error, as null is not does not pass the checks in the function above. 

For me, this causes me to be unable to use this plugin with Flipper, I'm using patch-package to circumvent this with a patch that removes the newly added null.

So my question is, why was the null added, and what purpose does it serve? 

I'm using the following software versions

Flipper Version 0.176.1 (50.0.0)
react-native-flipper 0.176.1
realm-flipper-plugin-device 1.0.27

Screenshot with patch removing the null

<img width="1676" alt="Screenshot 2022-12-29 at 01 58 33-min" src="https://user-images.githubusercontent.com/8508304/209893759-aece331d-25c6-4799-aeea-9038b0cbeae4.png">

Screenshot using the current version of this package (unpatched)

<img width="1677" alt="Screenshot 2022-12-29 at 02 00 33-min" src="https://user-images.githubusercontent.com/8508304/209893810-a931a898-b5e3-4904-a172-2a434502a503.png">

**Comment by gagik** [comment]
Hey!
Thanks for the detailed report, I believe the discrepancy between the null and the undefined being checked was unintentional. Could you try the latest release of the `realm-flipper-plugin-device`? It should work without the patch now.

**Comment by fendorio** [comment]
Hey - Thanks for the swift response, I can confirm upgrading to the new version resolves this issue without the patch, many thanks.
