### ISSUE TITLE
Some tables display their data as 'undefined'

### ISSUE THREAD

**Issue by fkranenburg** [realm/realm-flipper-plugin#122]
Some tables are not displaying their data. I have tables that are working fine but some tables do not. All data is displayed as 'undefined'. Is this a bug?

<img width="915" alt="image" src="https://user-images.githubusercontent.com/5680394/211655357-52804633-8472-4e7e-8567-255ae45a05cf.png">

**Comment by gagik** [comment]
Hey! Thank you for the report! 

- Would it be possible for you to share the schema of the table(s) that show undefined fields? 
- Do these objects have embedded objects, reference themselves and/or reference objects that reference themselves (i.e. have circular references)? 
- Could you also share what version of Realm you are using on the device?

Those might be factors why this could happen. We are currently working on a major revamp to how communication is done between the plugin and the device which should hopefully address most of this.

**Comment by fkranenburg** [comment]
> Would it be possible for you to share the schema of the table(s) that show undefined fields?

Yes, this is the current schema.

```
export const ClientAppointment = {
  name: "ClientAppointment",
  primaryKey: "id",
  isCommon: false,
  properties: {
    client: {
      type: "Client",
      indexed: false,
      optional: true
    },
    start: {
      type: "date",
      indexed: false,
      optional: true
    },
    end: {
      type: "date",
      indexed: false,
      optional: true
    },
    cancelled: {
      type: "bool",
      indexed: false,
      optional: true
    },
    professional: {
      type: "Person",
      indexed: false,
      optional: true
    },
    subject: {
      type: "string",
      indexed: false,
      optional: true
    },
    oneTimeChange: {
      type: "bool",
      indexed: false,
      optional: true
    },
    description: {
      type: "string",
      indexed: false,
      optional: true
    },
    executiveTeam: {
      type: "Team",
      indexed: false,
      optional: true
    },
    clientActions: {
      type: "list",
      objectType: "ClientAction",
      indexed: false
    },
    clientAppointmentKind: {
      type: "ClientAppointmentKind",
      indexed: false,
      optional: true
    },
    prestatie: {
      type: "Prestatie",
      indexed: false,
      optional: true
    },
    productKind: {
      type: "Constant",
      indexed: false,
      optional: true
    },
    kilometers: {
      type: "double",
      indexed: false,
      optional: true
    },
    transporttype: {
      type: "string",
      indexed: false,
      optional: true
    },
    reasonCancellation: {
      type: "Constant",
      indexed: false,
      optional: true
    },
    descriptionCancellation: {
      type: "string",
      indexed: false,
      optional: true
    },
    alternativeAddress: {
      type: "string",
      indexed: false,
      optional: true
    },
    budgetTeam: {
      type: "Team",
      indexed: false,
      optional: true
    },
    clientAppointmentArray: {
      type: "ClientAppointmentArray",
      indexed: false,
      optional: true
    },
    changeConditions: {
      type: "string[]",
      indexed: false,
      optional: true
    },
    planUnit: {
      type: "PlanUnit",
      indexed: false,
      optional: true
    },
    location: {
      type: "Location",
      indexed: false,
      optional: true
    },
    id: {
      type: "string",
      indexed: false,
      optional: false
    }
  }
};
```

> Do these objects have embedded objects, reference themselves and/or reference objects that reference themselves (i.e. have circular references)?

Yes, it could be we have circular references (but I do not know for sure). No embedded objects.

> Could you also share what version of Realm you are using on the device?

Version 11.3.1 of realm and version 1.0.28 of realm-flipper-plugin-device.

**Comment by gagik** [comment]
Hello again! The `realm-flipper-plugin` and `realm-flipper-plugin-device` have both been updated to version [v1.1.0](https://github.com/realm/realm-flipper-plugin/blob/main/flipper-plugin-realm/CHANGELOG.md) which should address this issue. Try upgrading both and see if all data seems correct.

**Comment by fkranenburg** [comment]
Just upgraded (and had to remove the realm flipper plugin manually from Flipper so it picked up the newer version automatically) and it works now. Great work! Thanks!
